// In this file you can specify the trial data for your experiment

const practice_trials = {
  key_press: [
    {
        picture: "images/practice/13_50_different.jpg",
        expected: "different",
        pic_number: 13,
        degree_of_rotation: 50,
        trial_type: 'practice',
        key1: "f",
        key2: "j",
        f: "same",
        j: "different",
    },
    {
        picture: "images/practice/13_50_same.jpg",
        expected: "same",
        pic_number: 13,
        degree_of_rotation: 50,
        trial_type: 'practice',
        key1: "f",
        key2: "j",
        f: "same",
        j: "different",
    },
    {
        picture: "images/practice/13_150_different.jpg",
        expected: "different",
        pic_number: 13,
        degree_of_rotation: 150,
        trial_type: 'practice',
        key1: "f",
        key2: "j",
        f: "same",
        j: "different",
    },
    {
        picture: "images/practice/13_150_same.jpg",
        expected: "same",
        pic_number: 13,
        degree_of_rotation: 150,
        trial_type: 'practice',
        key1: "f",
        key2: "j",
        f: "same",
        j: "different",
    },
    {
        picture: "images/practice/14_50_different.jpg",
        expected: "different",
        pic_number: 14,
        degree_of_rotation: 50,
        trial_type: 'practice',
        key1: "f",
        key2: "j",
        f: "same",
        j: "different",
    },
    {
        picture: "images/practice/14_50_same.jpg",
        expected: "same",
        pic_number: 14,
        degree_of_rotation: 50,
        trial_type: 'practice',
        key1: "f",
        key2: "j",
        f: "same",
        j: "different",
    },
    {
        picture: "images/practice/14_150_different.jpg",
        expected: "different",
        pic_number: 14,
        degree_of_rotation: 150,
        trial_type: 'practice',
        key1: "f",
        key2: "j",
        f: "same",
        j: "different",
    },
    {
        picture: "images/practice/14_150_same.jpg",
        expected: "same",
        pic_number: 14,
        degree_of_rotation: 150,
        trial_type: 'practice',
        key1: "f",
        key2: "j",
        f: "same",
        j: "different",
    },
    {
        picture: "images/practice/15_50_different.jpg",
        expected: "different",
        pic_number: 15,
        degree_of_rotation: 50,
        trial_type: 'practice',
        key1: "f",
        key2: "j",
        f: "same",
        j: "different",
    },
    {
        picture: "images/practice/15_50_same.jpg",
        expected: "same",
        pic_number: 15,
        degree_of_rotation: 50,
        trial_type: 'practice',
        key1: "f",
        key2: "j",
        f: "same",
        j: "different",
    },
    {
        picture: "images/practice/15_150_different.jpg",
        expected: "different",
        pic_number: 15,
        degree_of_rotation: 150,
        trial_type: 'practice',
        key1: "f",
        key2: "j",
        f: "same",
        j: "different",
    },
    {
        picture: "images/practice/15_150_same.jpg",
        expected: "same",
        pic_number: 15,
        degree_of_rotation: 150,
        trial_type: 'practice',
        key1: "f",
        key2: "j",
        f: "same",
        j: "different",
    }

  ]

};

const main_trials = {
    key_press: [
        {
            picture: "images/main/1_50_different.jpg",
            expected: "different",
            pic_number: 1,
            degree_of_rotation: 50,
            trial_type: 'main',
            key1: "f",
            key2: "j",
            f: "same",
            j: "different",
        },
        {
            picture: "images/main/1_50_same.jpg",
            expected: "same",
            pic_number: 1,
            degree_of_rotation: 50,
            trial_type: 'main',
            key1: "f",
            key2: "j",
            f: "same",
            j: "different",
        },
        {
            picture: "images/main/1_150_different.jpg",
            expected: "different",
            pic_number: 1,
            degree_of_rotation: 150,
            trial_type: 'main',
            key1: "f",
            key2: "j",
            f: "same",
            j: "different",
        },
        {
            picture: "images/main/1_150_same.jpg",
            expected: "same",
            pic_number: 1,
            degree_of_rotation: 150,
            trial_type: 'main',
            key1: "f",
            key2: "j",
            f: "same",
            j: "different",
        },
        {
            picture: "images/main/2_50_same.jpg",
            expected: "same",
            pic_number: 2,
            degree_of_rotation: 50,
            trial_type: 'main',
            key1: "f",
            key2: "j",
            f: "same",
            j: "different",
        },
        {
            picture: "images/main/2_50_different.jpg",
            expected: "different",
            pic_number: 2,
            degree_of_rotation: 50,
            trial_type: 'main',
            key1: "f",
            key2: "j",
            f: "same",
            j: "different",
        },
        {
            picture: "images/main/2_150_same.jpg",
            expected: "same",
            pic_number: 2,
            degree_of_rotation: 150,
            trial_type: 'main',
            key1: "f",
            key2: "j",
            f: "same",
            j: "different",
        },
        {
            picture: "images/main/2_150_different.jpg",
            expected: "different",
            pic_number: 2,
            degree_of_rotation: 150,
            trial_type: 'main',
            key1: "f",
            key2: "j",
            f: "same",
            j: "different",
        },
        {
            picture: "images/main/3_50_same.jpg",
            expected: "same",
            pic_number: 3,
            degree_of_rotation: 50,
            trial_type: 'main',
            key1: "f",
            key2: "j",
            f: "same",
            j: "different",
        },
        {
            picture: "images/main/3_50_different.jpg",
            expected: "different",
            pic_number: 3,
            degree_of_rotation: 50,
            trial_type: 'main',
            key1: "f",
            key2: "j",
            f: "same",
            j: "different",
        },
        {
            picture: "images/main/3_150_same.jpg",
            expected: "same",
            pic_number: 3,
            degree_of_rotation: 150,
            trial_type: 'main',
            key1: "f",
            key2: "j",
            f: "same",
            j: "different",
        },
        {
            picture: "images/main/3_150_different.jpg",
            expected: "different",
            pic_number: 3,
            degree_of_rotation: 150,
            trial_type: 'main',
            key1: "f",
            key2: "j",
            f: "same",
            j: "different",
        },
        {
            picture: "images/main/4_50_same.jpg",
            expected: "same",
            pic_number: 4,
            degree_of_rotation: 50,
            trial_type: 'main',
            key1: "f",
            key2: "j",
            f: "same",
            j: "different",
        },
        {
            picture: "images/main/4_50_different.jpg",
            expected: "different",
            pic_number: 4,
            degree_of_rotation: 50,
            trial_type: 'main',
            key1: "f",
            key2: "j",
            f: "same",
            j: "different",
        },
        {
            picture: "images/main/4_150_same.jpg",
            expected: "same",
            pic_number: 4,
            degree_of_rotation: 150,
            trial_type: 'main',
            key1: "f",
            key2: "j",
            f: "same",
            j: "different",
        },
        {
            picture: "images/main/4_150_different.jpg",
            expected: "different",
            pic_number: 4,
            degree_of_rotation: 150,
            trial_type: 'main',
            key1: "f",
            key2: "j",
            f: "same",
            j: "different",
        },
        {
            picture: "images/main/5_50_same.jpg",
            expected: "same",
            pic_number: 5,
            degree_of_rotation: 50,
            trial_type: 'main',
            key1: "f",
            key2: "j",
            f: "same",
            j: "different",
        },
        {
            picture: "images/main/5_50_different.jpg",
            expected: "different",
            pic_number: 5,
            degree_of_rotation: 50,
            trial_type: 'main',
            key1: "f",
            key2: "j",
            f: "same",
            j: "different",
        },
        {
            picture: "images/main/5_150_same.jpg",
            expected: "same",
            pic_number: 5,
            degree_of_rotation: 150,
            trial_type: 'main',
            key1: "f",
            key2: "j",
            f: "same",
            j: "different",
        },
        {
            picture: "images/main/5_150_different.jpg",
            expected: "different",
            pic_number: 5,
            degree_of_rotation: 150,
            trial_type: 'main',
            key1: "f",
            key2: "j",
            f: "same",
            j: "different",
        },
        {
            picture: "images/main/6_50_same.jpg",
            expected: "same",
            pic_number: 6,
            degree_of_rotation: 50,
            trial_type: 'main',
            key1: "f",
            key2: "j",
            f: "same",
            j: "different",
        },
        {
            picture: "images/main/6_50_different.jpg",
            expected: "different",
            pic_number: 6,
            degree_of_rotation: 50,
            trial_type: 'main',
            key1: "f",
            key2: "j",
            f: "same",
            j: "different",
        },
        {
            picture: "images/main/6_150_same.jpg",
            expected: "same",
            pic_number: 6,
            degree_of_rotation: 150,
            trial_type: 'main',
            key1: "f",
            key2: "j",
            f: "same",
            j: "different",
        },
        {
            picture: "images/main/6_150_different.jpg",
            expected: "different",
            pic_number: 6,
            degree_of_rotation: 150,
            trial_type: 'main',
            key1: "f",
            key2: "j",
            f: "same",
            j: "different",
        },
        {
            picture: "images/main/7_50_same.jpg",
            expected: "same",
            pic_number: 7,
            degree_of_rotation: 50,
            trial_type: 'main',
            key1: "f",
            key2: "j",
            f: "same",
            j: "different",
        },
        {
            picture: "images/main/7_50_different.jpg",
            expected: "different",
            pic_number: 7,
            degree_of_rotation: 50,
            trial_type: 'main',
            key1: "f",
            key2: "j",
            f: "same",
            j: "different",
        },
        {
            picture: "images/main/7_150_same.jpg",
            expected: "same",
            pic_number: 7,
            degree_of_rotation: 150,
            trial_type: 'main',
            key1: "f",
            key2: "j",
            f: "same",
            j: "different",
        },
        {
            picture: "images/main/7_150_different.jpg",
            expected: "different",
            pic_number: 7,
            degree_of_rotation: 150,
            trial_type: 'main',
            key1: "f",
            key2: "j",
            f: "same",
            j: "different",
        },

        {
            picture: "images/main/8_50_same.jpg",
            expected: "same",
            pic_number: 8,
            degree_of_rotation: 50,
            trial_type: 'main',
            key1: "f",
            key2: "j",
            f: "same",
            j: "different",
        },
        {
            picture: "images/main/8_50_different.jpg",
            expected: "different",
            pic_number: 8,
            degree_of_rotation: 50,
            trial_type: 'main',
            key1: "f",
            key2: "j",
            f: "same",
            j: "different",
        },
        {
            picture: "images/main/8_150_same.jpg",
            expected: "same",
            pic_number: 8,
            degree_of_rotation: 150,
            trial_type: 'main',
            key1: "f",
            key2: "j",
            f: "same",
            j: "different",
        },
        {
            picture: "images/main/8_150_different.jpg",
            expected: "different",
            pic_number: 8,
            degree_of_rotation: 150,
            trial_type: 'main',
            key1: "f",
            key2: "j",
            f: "same",
            j: "different",
        },
        {
            picture: "images/main/9_50_same.jpg",
            expected: "same",
            pic_number: 9,
            degree_of_rotation: 50,
            trial_type: 'main',
            key1: "f",
            key2: "j",
            f: "same",
            j: "different",
        },
        {
            picture: "images/main/9_50_different.jpg",
            expected: "different",
            pic_number: 9,
            degree_of_rotation: 50,
            trial_type: 'main',
            key1: "f",
            key2: "j",
            f: "same",
            j: "different",
        },
        {
            picture: "images/main/9_150_same.jpg",
            expected: "same",
            pic_number: 9,
            degree_of_rotation: 150,
            trial_type: 'main',
            key1: "f",
            key2: "j",
            f: "same",
            j: "different",
        },
        {
            picture: "images/main/9_150_different.jpg",
            expected: "different",
            pic_number: 9,
            degree_of_rotation: 150,
            trial_type: 'main',
            key1: "f",
            key2: "j",
            f: "same",
            j: "different",
        },
        {
            picture: "images/main/10_50_same.jpg",
            expected: "same",
            pic_number: 10,
            degree_of_rotation: 50,
            trial_type: 'main',
            key1: "f",
            key2: "j",
            f: "same",
            j: "different",
        },
        {
            picture: "images/main/10_50_different.jpg",
            expected: "different",
            pic_number: 10,
            degree_of_rotation: 50,
            trial_type: 'main',
            key1: "f",
            key2: "j",
            f: "same",
            j: "different",
        },
        {
            picture: "images/main/10_150_same.jpg",
            expected: "same",
            pic_number: 10,
            degree_of_rotation: 150,
            trial_type: 'main',
            key1: "f",
            key2: "j",
            f: "same",
            j: "different",
        },
        {
            picture: "images/main/10_150_different.jpg",
            expected: "different",
            pic_number: 10,
            degree_of_rotation: 150,
            trial_type: 'main',
            key1: "f",
            key2: "j",
            f: "same",
            j: "different",
        },
        {
            picture: "images/main/11_50_same.jpg",
            expected: "same",
            pic_number: 11,
            degree_of_rotation: 50,
            trial_type: 'main',
            key1: "f",
            key2: "j",
            f: "same",
            j: "different",
        },
        {
            picture: "images/main/11_50_different.jpg",
            expected: "different",
            pic_number: 11,
            degree_of_rotation: 50,
            trial_type: 'main',
            key1: "f",
            key2: "j",
            f: "same",
            j: "different",
        },
        {
            picture: "images/main/11_150_same.jpg",
            expected: "same",
            pic_number: 11,
            degree_of_rotation: 150,
            trial_type: 'main',
            key1: "f",
            key2: "j",
            f: "same",
            j: "different",
        },
        {
            picture: "images/main/11_150_different.jpg",
            expected: "different",
            pic_number: 11,
            degree_of_rotation: 150,
            trial_type: 'main',
            key1: "f",
            key2: "j",
            f: "same",
            j: "different",
        },
        {
            picture: "images/main/12_50_same.jpg",
            expected: "same",
            pic_number: 12,
            degree_of_rotation: 50,
            trial_type: 'main',
            key1: "f",
            key2: "j",
            f: "same",
            j: "different",
        },
        {
            picture: "images/main/12_50_different.jpg",
            expected: "different",
            pic_number: 12,
            degree_of_rotation: 50,
            trial_type: 'main',
            key1: "f",
            key2: "j",
            f: "same",
            j: "different",
        },
        {
            picture: "images/main/12_150_same.jpg",
            expected: "same",
            pic_number: 12,
            degree_of_rotation: 150,
            trial_type: 'main',
            key1: "f",
            key2: "j",
            f: "same",
            j: "different",
        },
        {
            picture: "images/main/12_150_different.jpg",
            expected: "different",
            pic_number: 12,
            degree_of_rotation: 150,
            trial_type: 'main',
            key1: "f",
            key2: "j",
            f: "same",
            j: "different",
        }

    ]

};
